spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?&useTimezone=true&serverTimezone=UTC
    initialization-mode: always
    username: sfg_dev_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: database_create.sql