# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests! and gen code coverage
      - run: mvn integration-test cobertura:cobertura

      - store_test_results:
          path: target/surefire-reports

      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)


#version: 2
#jobs:
#  maven/test:
#    docker:
#      - image: circleci/openjdk:11-jdk-node
#
#
#        working_directory: ~/repo
#
#          environment:
#            # Customize the JVM maximum heap limit
#            MAVEN_OPTS: -Xmx3200m
#
#          steps:
#            - checkout
#
#            # Download and cache dependencies
#            - restore_cache:
#                keys:
#                  - v1-dependencies-{{ checksum "pom.xml" }}
#                  # fallback to using the latest cache if no exact match is found
#                  - v1-dependencies-
#
#            - run: mvn dependency:go-offline
#
#            - save_cache:
#                paths:
#                  - ~/.m2
#                key: v1-dependencies-{{ checksum "pom.xml" }}
#
#            # run tests! and gen code coverage
#            - run: mvn integration-test cobertura:cobertura
#
#            - store_test_results:
#                path: target/surefire-reports
#
#            - run:
#                name: Send to CodeCov
#                command: bash <(curl -s https://codecov.io/bash)
##    steps:
##      - checkout
##      - run:
##          name: Generate Cache Checksum
##          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
##      - restore_cache:
##          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
##      - run:
##          name: Install Dependencies
##          command: mvn dependency:go-offline --settings 'pom.xml'
##      - run:
##          name: Run Tests
##          command: mvn verify --settings 'pom.xml'
##      - save_cache:
##          paths:
##            - ~/.m2
##          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
##      - store_test_results:
##          path: target/surefire-reports
##workflows:
##  maven_test:
##    jobs:
##      - maven/test
##  version: 2
#
## Original config.yml file:
## version: 2.1
##
## orbs:
##   maven: circleci/maven@0.0.12
##
## workflows:
##   maven_test:
##     jobs:
##       - maven/test # checkout, build, test, and upload test results